### ISSUE TITLE
error in def_voxel_set_abstraction.py

### ISSUE THREAD

**Issue by MengAaron** [AutoVision-cloud/Deformable-PV-RCNN#1]
My code runs well on OpenPCDet, but got an error in Deformable-PV-RCNN,can you help me?
File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/backbones_3d/pfe/def_voxel_set_abstraction.py", line 13, in __init__
    super(Self_Attention, self).__init__()
NameError: name 'Self_Attention' is not defined

**Comment by AutoVision-cloud** [comment]
A bug in the naming conventions has been fixed and the current version should work now.

**Comment by MengAaron** [comment]
that problem has been solved. But I meet another problem, as bellow. I verify that code work well on pv-rcnn, but get error on deformable-pv-rcnn
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 115, in main
    model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=train_set)
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/__init__.py", line 11, in build_network
    model_cfg=model_cfg, num_class=num_class, dataset=dataset
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/detectors/__init__.py", line 20, in build_detector
    model_cfg=model_cfg, num_class=num_class, dataset=dataset
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/detectors/pv_rcnn.py", line 7, in __init__
    self.module_list = self.build_networks()
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/detectors/detector3d_template.py", line 45, in build_networks
    model_info_dict=model_info_dict
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/detectors/detector3d_template.py", line 129, in build_dense_head
    predict_boxes_when_training=self.model_cfg.get('ROI_HEAD', False)
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/dense_heads/anchor_head_single.py", line 12, in __init__
    predict_boxes_when_training=predict_boxes_when_training
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/dense_heads/anchor_head_template.py", line 32, in __init__
    self.target_assigner = self.get_target_assigner(anchor_target_cfg)
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/dense_heads/anchor_head_template.py", line 67, in get_target_assigner
    match_height=anchor_target_cfg.MATCH_HEIGHT
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/dense_heads/target_assigner/axis_aligned_target_assigner.py", line 17, in __init__
    self.anchor_class_names = [config['class_name'] for config in anchor_generator_cfg]
  File "/remote-home/my/Deformable-PV-RCNN/OpenPCDet/pcdet/models/dense_heads/target_assigner/axis_aligned_target_assigner.py", line 17, in <listcomp>
    self.anchor_class_names = [config['class_name'] for config in anchor_generator_cfg]
KeyError: 'class_name'

**Comment by AutoVision-cloud** [comment]
In this project, we have submoduled commit `b32fbdd`. We suggest cloning the repository with this submodule and building the library from scratch with `python setup.py develop`.  Since OpenPCDet is under active development, this error is because the config files have changed recently from the ones that we provide and were use for the experiment.

**Comment by AutoVision-cloud** [comment]
We have now added compatibility for pcdet-v0.3.
